### ISSUE TITLE
thread 'main' panicked at 'Too many open files. Please reduce batch size.' in kali on WSL2

### ISSUE THREAD

**Issue by fuomag9** [brandonskerritt/RustScan#39]
I've installed the latest .deb from the release page on WSL2 kali and it crashes when doing a scan. I have nmap installed.
```
kali@Anonymous:/tmp$ rustscan 192.168.1.140

     _____           _    _____
    |  __ \         | |  / ____|
    | |__) |   _ ___| |_| (___   ___ __ _ _ __
    |  _  / | | / __| __|\___ \ / __/ _` | '_ \
    | | \ \ |_| \__ \ |_ ____) | (_| (_| | | | |
    |_|  \_\__,_|___/\__|_____/ \___\__,_|_| |_|
    Faster nmap scanning with rust.
 Automated Decryption Tool - https://github.com/ciphey/ciphey
 Creator https://github.com/brandonskerritt
Open 80
Os { code: 24, kind: Other, message: "Too many open files" }
thread 'main' panicked at 'Too many open files. Please reduce batch size. The default is 5000. Try -b 2500.', src/main.rs:179:21
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by brandonskerritt** [comment]
Hey!

You need to decrease the batch size as your OS doesn't support that. Or increase your OS' batch size. 

Run this: 

ulimit -a
ulimit -Hn
ulimit -Sn

This will tell you how many open files you're allowed at any given time. Reduce the batch size to either that number or below.

Alternatively, increase the batch size of your OS.  Use ulimit -n to do this, where the flag for -n is how much you are comfortable with. For RustScan, the default is 5000.

**Comment by fuomag9** [comment]
Unfortunately kali linux on WSL2 doesn't seem to have ulimit?
```
sudo ulimit -n 5000
[sudo] password for kali:
sudo: ulimit: command not found
```

**Comment by fuomag9** [comment]
I still get the same error

```
kali@Anonymous:/tmp$ sudo sh -c "ulimit -n 5000"
kali@Anonymous:/tmp$ rustscan 192.168.1.140

     _____           _    _____
    |  __ \         | |  / ____|
    | |__) |   _ ___| |_| (___   ___ __ _ _ __
    |  _  / | | / __| __|\___ \ / __/ _` | '_ \
    | | \ \ |_| \__ \ |_ ____) | (_| (_| | | | |
    |_|  \_\__,_|___/\__|_____/ \___\__,_|_| |_|
    Faster nmap scanning with rust.
 Automated Decryption Tool - https://github.com/ciphey/ciphey
 Creator https://github.com/brandonskerritt
Open 80
Os { code: 24, kind: Other, message: "Too many open files" }
thread 'main' panicked at 'Too many open files. Please reduce batch size. The default is 5000. Try -b 2500.', src/main.rs:179:21
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
kali@Anonymous:/tmp$ sudo rustscan 192.168.1.140

     _____           _    _____
    |  __ \         | |  / ____|
    | |__) |   _ ___| |_| (___   ___ __ _ _ __
    |  _  / | | / __| __|\___ \ / __/ _` | '_ \
    | | \ \ |_| \__ \ |_ ____) | (_| (_| | | | |
    |_|  \_\__,_|___/\__|_____/ \___\__,_|_| |_|
    Faster nmap scanning with rust.
 Automated Decryption Tool - https://github.com/ciphey/ciphey
 Creator https://github.com/brandonskerritt
Os { code: 24, kind: Other, message: "Too many open files" }
thread 'main' panicked at 'Too many open files. Please reduce batch size. The default is 5000. Try -b 2500.', src/main.rs:179:21
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by brandonskerritt** [comment]
It looks like WSL doesn't support ulimit :-( 

https://github.com/microsoft/WSL/issues/1679

**Comment by fuomag9** [comment]
> 
> 
> It looks like WSL doesn't support ulimit :-(
> 
> [microsoft/WSL#1679](https://github.com/microsoft/WSL/issues/1679)

Damn, ironically using docker worked fine

**Comment by brandonskerritt** [comment]
I'm writing documentation for this issue, so thanks for bringing it up!

PS: I'm releasing a Docker version maybe tomorrow? That way people don't have to sweat about ulimit stuff 🤷‍♂️✨
